raaz-core/Raaz/Core/Random.hs, raaz-core/raaz-core.cabal, raaz-core/src/urandom/Raaz/System/Random.hs
This is the new style pseudo-random generator that I wanted to add to
the raaz-crypto library. We can discuss this before I merge it into
raaz-crypto
=> New style Pseudo-random generator

raaz-core/Raaz/Core/Classes.hs, raaz-core/Raaz/Core/Parse/Applicative.hs, raaz-core/Raaz/Core/Types/Word.hs, raaz-core/Raaz/Core/Write.hs, raaz-core/raaz-core.cabal
This pull request is geared towards addressing issue #214 and adds
basic infrastructure to work with vectors. It gives the following
stuffs.
1. Unbox instances for the endian safe types. Need to work with
unboxed vectors of these values.
2. Timing safe comparisons of vectors
3. Parsing and writing vectors.
=> bring vectors into the picture

raaz-core/Raaz/Core/Classes.hs, raaz-core/Raaz/Core/Test/EndianStore.hs, raaz-core/Raaz/Core/Util/Ptr.hs
- ALIGN length type
- secure version of allocaBuffer
=> some changes that will set the stage for the new memory subsystem

raaz-core/Raaz/Core/MonoidalAction.hs, raaz-core/Raaz/Core/Parse/Applicative.hs, raaz-core/Raaz/Core/Write.hs
Some cleanup an simplification of monoidal action
=> cleanup monoidal actions

.travis.yml, Raaz/Core/Encode/Internal.hs, Raaz/Core/MonoidalAction.hs, Raaz/Core/Parse/Applicative.hs, Raaz/Core/Primitives/Hash.hs, Raaz/Core/Types.hs, Raaz/Core/Types/Word.hs, Raaz/Core/Util/ByteString.hs, Raaz/Core/Util/Ptr.hs, Raaz/Core/Write.hs, Raaz/Hash/Blake256/CPortable.hs, Raaz/Hash/Blake256/Instance.hs, Raaz/Hash/Blake256/Ref.hs, Raaz/Hash/Blake256/Type.hs, Raaz/Hash/HMAC.hs, Raaz/Hash/Sha1/Ref.hs, spec/Raaz/Core/Encode/Base16Spec.hs, spec/Raaz/Core/Util/ByteStringSpec.hs
This is the branch where we work towards merging all the subpackages. I have also moved the tests to HSpec from testframework.
=> X merge packages

raaz.cabal
The monad interface for memory operations can help simplify writing of memory operations.
=> A monad for memory operations.

.travis.yml
=> travis: build for osx as well

raaz.cabal, spec/Raaz/Core/SystemPRGSpec.hs
Write tests to check system dependent stuff like system wide prg, memory locking etc.
=> specs for system resources

Raaz/Core/Memory.hs, Raaz/Core/MonoidalAction.hs, Raaz/Core/Parse/Applicative.hs, Raaz/Core/Types/Pointer.hs, Raaz/Core/Write.hs, benchmarks/BlazeVsWrite.hs, raaz.cabal
add benchmark for writes and the associated performance tuning
=> performance tweaks for writes

Raaz/Core/Types/Endian.hs, Raaz/Core/Write.hs, benchmarks/BlazeVsWrite.hs, raaz.cabal
Added benchmarks for endian types as well
=> Some more benchmarks

.travis.yml
Mostly reorganized the addons section.
=> travis: some cleanup

Raaz/Core/Primitives.hs, Raaz/Core/Types.hs, Raaz/Core/Types/Describe.hs, Raaz/Hash/Internal.hs, Raaz/Hash/Sha/Util.hs, Raaz/Hash/Sha1/Internal.hs, Raaz/Hash/Sha256/Internal.hs, Raaz/Hash/Sha512/Internal.hs, raaz.cabal
This is a minor pull reques that addes decriptive names and info to implementations of primitives.
=> Added descriptions to implementation.

Raaz/Core/Primitives.hs, Raaz/Hash/Internal.hs, Raaz/Hash/Internal/HMAC.hs, Raaz/Hash/Sha1.hs, Raaz/Hash/Sha1/Implementation/CPortable.hs, Raaz/Hash/Sha1/Internal.hs, Raaz/Hash/Sha1/Recommendation.hs, Raaz/Hash/Sha224.hs, Raaz/Hash/Sha224/Implementation/CPortable.hs, Raaz/Hash/Sha224/Internal.hs, Raaz/Hash/Sha224/Recommendation.hs, Raaz/Hash/Sha256.hs, Raaz/Hash/Sha256/Implementation/CPortable.hs, Raaz/Hash/Sha256/Internal.hs, Raaz/Hash/Sha256/Recommendation.hs, Raaz/Hash/Sha384.hs, Raaz/Hash/Sha384/Implementation/CPortable.hs, Raaz/Hash/Sha384/Internal.hs, Raaz/Hash/Sha384/Recommendation.hs, Raaz/Hash/Sha512.hs, Raaz/Hash/Sha512/Implementation/CPortable.hs, Raaz/Hash/Sha512/Internal.hs, Raaz/Hash/Sha512/Recommendation.hs, raaz.cabal, spec/Common/Hash.hs
seperate out the recommendation for an implementation.
=> Separate recommendation

raaz.cabal, spec/Common/Instances.hs
I dont believe users need hashes in any way
=> hide the internals of all hashes.

Raaz/Hash/Sha1.hs, Raaz/Hash/Sha224/Internal.hs, Raaz/Hash/Sha512/Internal.hs, raaz.cabal
- Hide the Hman internals and fix some warnings
=> some cleanup 

Raaz/Core/ByteSource.hs, Raaz/Core/Encode/Internal.hs, Raaz/Core/Memory.hs, Raaz/Core/Primitives.hs, Raaz/Core/Types/Endian.hs, Raaz/Core/Types/Pointer.hs, Raaz/Core/Write.hs
=> Length units: getting rid of Num instance

raaz.cabal
Better cabal bounds as suggested by @hvr
=> update the cabal version to >=1.10

.travis.yml, raaz.cabal
=> travis: debian-8 build.

Raaz/Core/Types/Tuple.hs
There is only one place where we now have a cpp macro.
=> refactor the version depenedent code in Tuple.hs

Raaz/Core/Parse/Applicative.hs, Raaz/Core/Transfer.hs, Raaz/Core/Types.hs, Raaz/Core/Types/Endian.hs, Raaz/Core/Types/Equality.hs, Raaz/Core/Types/Tuple.hs, Raaz/Hash/Internal/HMAC.hs, cbits/raaz/core/endian.c, cbits/raaz/core/endian.h, spec/Common/Utils.hs
Now the `EndianStore` instance has an `adjustEndian` function.
=> Preparation for blake 

.travis.yml
This build supports stack based builds for travis
=> travis: stack based build.

cbits/raaz/core/endian.c, cbits/raaz/core/endian.h, cbits/raaz/hash/sha1/portable.c, cbits/raaz/hash/sha256/portable.c, cbits/raaz/hash/sha512/portable.c, raaz.cabal
this is some cleanup for the C based endian code.
=> Cleanup endian further

.travis.yml, Raaz/Cipher/AES/Internal.hs, Raaz/Cipher/ChaCha20.hs, Raaz/Cipher/ChaCha20/Implementation/CPortable.hs, Raaz/Cipher/ChaCha20/Implementation/GCCVector.hs, Raaz/Cipher/ChaCha20/Internal.hs, Raaz/Cipher/Internal.hs, benchmarks/Cipher.hs, cbits/raaz/cipher/chacha20/common.h, cbits/raaz/cipher/chacha20/cportable.c, cbits/raaz/cipher/chacha20/cportable.h, cbits/raaz/cipher/chacha20/vector.c, cbits/raaz/cipher/chacha20/vector.h, raaz.cabal, spec/Common/Cipher.hs, spec/Common/Imports.hs, spec/Raaz/Cipher/ChaCha20Spec.hs, stack-travis.yaml, stack.yaml
Currently this is only as good as the non-vector implementations. But here is a skeleton.
=> Vector implementation of chacha20

cbits/raaz/cipher/chacha20/vector.c
Minor change to make things work with clang.
=> updated vector implementation to compile with clang as well.

Raaz/Cipher/ChaCha20/Implementation/Vector128.hs, Raaz/Cipher/ChaCha20/Implementation/Vector256.hs, benchmarks/Cipher.hs, cbits/raaz/cipher/chacha20/common.h, cbits/raaz/cipher/chacha20/vector.h, cbits/raaz/cipher/chacha20/vector128.c, cbits/raaz/cipher/chacha20/vector256.c, raaz.cabal, spec/Common/Cipher.hs, spec/Raaz/Cipher/ChaCha20Spec.hs, stack.yaml
This pull request includes implementation that uses vectors of 256 size. Gives better performance on
for example x86_64 with avx extension.
=> Vector256 chacha20

Raaz/Cipher/ChaCha20/Implementation/CPortable.hs, Raaz/Cipher/ChaCha20/Internal.hs, Raaz/Core/Types.hs, Raaz/Core/Types/Aligned.hs, cbits/raaz/cipher/chacha20/cportable.c, cbits/raaz/cipher/chacha20/vector256.c, raaz.cabal
- some cleanup in chaca code
- added Align128, Align256 types
=> Some minor improvements

Raaz/Cipher/ChaCha20/Implementation/CPortable.hs, Raaz/Cipher/ChaCha20/Recommendation.hs, Reviewing.md, cbits/raaz/cipher/chacha20/cportable.c, raaz.cabal, stack.yaml
Flags to let loose GCC  vectorisation. Now submitted to the release branch
See #302
=> Flag to nativise and vectorise

.travis.yml
This is an attempt to fix irc notifications.
=> irc notification fixes.

cbits/raaz/core/endian.h, raaz.cabal
Now hopefully will work better on bsds.
=> more portable endian processing

Raaz/Core/ByteSource.hs, raaz.cabal, spec/Raaz/Core/ByteSourceSpec.hs
* Fixed a bug in instance for list of source
* Tighten the condition of source exhaustion
=> correcting defficiency in bytesource.

.gitignore, .travis.yml, Raaz/Core/Encode/Base16.hs, Raaz/Core/Encode/Base64.hs, liquid/LiquidSpec.hs, raaz.cabal, stack-liquidhaskell.yaml
Basic liquid haskell integration.
- A travis build that will run liquid haskell (Need to find ways to make it efficient diff)
No interesting specs added yet.
=> Proof of concept Liquid haskell integration

README.md, appveyor.yml, cbits/raaz/core/endian.c
=> minimalist appveyor.yml file.

cbits/raaz/core/endian.h, raaz.cabal
use windows native byte swapping.
=> byte swapping on windows.

appveyor.yml
=> multiple builds for appveyor.

Raaz/Core/Types/Pointer.hs, cbits/raaz/core/endian.c, cbits/raaz/core/memory.c, cbits/raaz/core/memory.h, entropy/windows/Raaz/Entropy.hsc, raaz.cabal
This should fix #280 and #281
All tests pass.
=> Raaz windows support

.gitmodules, .travis.yml
As outlined in the reddit post
https://www.reddit.com/r/haskell/comments/70f045/making_the_wiki_a_submodule_of_the_main_repo/
=> Making raaz wiki a submodule.

.travis.yml, Raaz/Core/Types/Pointer.hs, appveyor.yml
This is the starting point of the backpack branch of raaz. Backpack is expected to cleanup raaz quite a
bit. This is the starting of an experimental branch of raaz.
=> start building on backpack branch

.travis.yml, raaz.cabal
=> CI: updates to use the new-build (reissued to raaz:backpack branch)

.travis.yml, CHANGELOG.md, Raaz/Core/Encode/Base16.hs, Raaz/Core/Encode/Base64.hs, Raaz/Core/MonoidalAction.hs, Raaz/Core/Primitives.hs, Raaz/Core/Transfer.hs, Raaz/Core/Types/Equality.hs, Raaz/Core/Types/Pointer.hs, Raaz/Hash/Internal.hs, benchmarks/BenchPrimitives.hs
=> Added Semigroup instances

.gitmodules, .travis.yml, CHANGELOG.md, appveyor.yml, implementation/Blake2b/CPortable.hs, implementation/ChaCha20/CPortable.hs, implementation/Sha256/CPortable.hs, implementation/Sha512/CPortable.hs, raaz.cabal
This pull request gets libverse implementations into raaz. The status of various primitives is given below
=> integration of libverse

.travis.yml, appveyor.yml, benchmarks/Main.hs, benchmarks/internal/Benchmark/Types.hs, implementation/Blake2b/CHandWritten.hs, implementation/Blake2b/CPortable.hs, implementation/Blake2s/CHandWritten.hs, implementation/ChaCha20/CHandWritten.hs, implementation/ChaCha20/CPortable.hs, implementation/Sha256/CHandWritten.hs, implementation/Sha256/CPortable.hs, implementation/Sha512/CHandWritten.hs, implementation/Sha512/CPortable.hs, raaz.cabal
We have introduces handwritten implementations again so as to compare it with that exposed by verse.
The output of the benchmarking code is now in csv for better comparison.
=> Handwritten C implementations added to the mix

.travis.yml, core/Raaz/Core/Memory.hs, core/Raaz/Core/Types/Pointer.hs, core/cbits/raaz/core/memory.c, indef/ChaCha20/PRG.hs, raaz.cabal
=> Wiping memory

.travis.yml
As an alternative to haskell-ci we attempt a simplified version of travis.
=> simpilfication of travis.

.travis.yml
Avoid unnecessary package downloads.
=> travis: more efficient package installation.

.travis.yml, appveyor.yml, core/Raaz/Core/Prelude.hs, core/Raaz/Core/Types/Endian.hs, core/Raaz/Core/Types/Equality.hs, indef/auth/Interface.hs, indef/digest/hash/Interface.hs, indef/random/Entropy.hsig, indef/random/Implementation.hsig, indef/random/Interface.hs, indef/random/PRGenerator.hs, raaz.cabal, raaz/Raaz/Auth.hs, raaz/Raaz/Digest.hs, raaz/Raaz/V1/Auth.hs, raaz/Raaz/V1/Digest.hs
Clean up package to make use of cabal 3's new features
=> Working towards cabal 3

monocypher-2.0.6/cbits/monocypher.c, monocypher-2.0.6/cbits/monocypher.h, monocypher-2.0.6/cbits/optional/sha512.c, monocypher-2.0.6/cbits/optional/sha512.h, monocypher-2.0.6/tests/Monocypher.hs, monocypher-2.0.6/tests/Monocypher/Blake2bSpec.hs, monocypher-2.0.6/tests/Monocypher/Sha512Spec.hs, raaz.cabal
quick check tests against Blake2 and sha512 implementations in monocypher
=> Monocypher

CHANGELOG.md, core/Raaz/Core/Memory.hs, core/Raaz/Core/Types/Pointer.hs, core/Raaz/Primitive/ChaCha20/Internal.hs, implementation/ChaCha20/CPortable.hs, indef/Utils.hs, indef/chacha20/Implementation.hsig, indef/chacha20/XChaCha20/Implementation.hs, monocypher-2.0.6/cbits/encrypt.c, monocypher-2.0.6/tests/Monocypher/Blake2bSpec.hs, monocypher-2.0.6/tests/Monocypher/ChaCha20Spec.hs, monocypher-2.0.6/tests/Monocypher/Sha512Spec.hs, raaz.cabal, raaz/Raaz.hs, raaz/Raaz/Auth.hs, raaz/Raaz/Encrypt.hs, raaz/Raaz/V1/Encrypt.hs, tests/Raaz/Cipher/ChaCha20Spec.hs, tests/Raaz/Cipher/XChaCha20Spec.hs, tests/Raaz/Core/MemorySpec.hs
more monocypher tests and exposure of encrypt interface
=> Encryption and testing with monocypher

CHANGELOG.md, api/aead/Auth/Implementation.hsig, api/aead/Cipher/Implementation.hsig, api/aead/Interface.hs, core/Raaz/Core/Encode/Internal.hs, core/Raaz/Core/Transfer.hs, core/Raaz/Core/Types/Endian.hs, indef/buffer/Buffer.hs, monocypher/tests/Monocypher/ChaCha20Spec.hs, raaz.cabal, raaz/Raaz.hs, raaz/Raaz/AuthEncrypt.hs, raaz/Raaz/V1/AuthEncrypt.hs
This pull request incorporates encrypted authentication with ChaCha20Poly1305 and its XChaCha variant.
=> Chacha20 poly1305

.github/actions/cabal.yml, .github/actions/setup-mac.yml, .github/workflows/source-code-checks.yml, core/Raaz/Primitive/Blake2/Internal.hs, core/Raaz/Primitive/Keyed/Internal.hs, core/Raaz/Primitive/Sha2/Internal.hs
Some github actions and workflows
=> GitHub action

core/Raaz/Core/Util/ByteString.hs
=> remove unwanted module imports.

.github/workflows/checks.yml, .github/workflows/ci.yml, README.md, raaz.cabal
Bumping the bytestring version
=> dependency version bumpup.

.github/workflows/ci.yml
=> add windows build on github actions.

.github/workflows/checks.yml, .github/workflows/ci.yml, CHANGELOG.md, README.md, appveyor.yml, benchmarks/BenchPrimitives.hs, raaz.cabal
This is the changes for getting the 0.2.* branch uptodate with the latest ghc
=> Updates for a new release of the 0.2.* 

.github/workflows/ci.yml
=> action update

.github/workflows/ci.yml, raaz.cabal
New ghc version so update base
=> Base update

api/digest/Implementation.hsig, api/digest/Interface.hs, indef/buffer/Context.hs, raaz.cabal, raaz/Raaz.hs, raaz/Raaz/Digest.hs, raaz/Raaz/V1/Digest.hs, tests/Raaz/Digest/Blake2Spec.hs, tests/Raaz/Digest/Sha256Spec.hs, tests/Raaz/Digest/Sha512Spec.hs, tests/core/Tests/Core/Utils.hs, tests/message-digest/Tests/Digest.hs
This commit adds an incremental interface for message digest
=> Incremental interface for message digest

api/aead/Cipher/Implementation.hsig, api/auth/Implementation.hsig, api/digest/Implementation.hsig, implementation/Poly1305/CPortable.hs, indef/keyed/hash/Mac/Implementation.hs, raaz.cabal, tests/Raaz/Digest/Blake2Spec.hs, tests/Raaz/Mac/Poly1305Spec.hs, tests/auth/Implementation.hsig, tests/auth/Tests/Auth.hs, tests/auth/implementation/Auth/Mac/Blake2b.hs, tests/auth/implementation/Auth/Mac/Blake2s.hs, tests/auth/implementation/Auth/Poly1305.hs, tests/core/Tests/Core/Instances.hs, tests/message-digest/Implementation.hsig
Incremental algorithm for message auth tested against usual message auth
=> Incremental

api/aead/Interface.hs, api/auth/Interface.hs, api/digest/Interface.hs, api/random/Implementation.hsig, benchmarks/internal/Benchmark/CSPRG.hs, benchmarks/internal/Benchmark/Primitive.hs, benchmarks/internal/Benchmark/Types.hs, implementation/Blake2b/CHandWritten.hs, implementation/Blake2b/CPortable.hs, implementation/Blake2s/CHandWritten.hs, implementation/ChaCha20/CHandWritten.hs, implementation/ChaCha20/CPortable.hs, implementation/ChaCha20/Random/CPortable.hs, implementation/Poly1305/CPortable.hs, implementation/Sha256/CHandWritten.hs, implementation/Sha256/CPortable.hs, implementation/Sha512/CHandWritten.hs, implementation/Sha512/CPortable.hs, indef/Implementation.hsig, indef/chacha20/XChaCha20/Implementation.hs, indef/keyed/hash/Mac/Implementation.hs, raaz/Raaz/Auth.hs, raaz/Raaz/AuthEncrypt.hs, raaz/Raaz/Digest.hs, raaz/Raaz/V1/Auth.hs, raaz/Raaz/V1/AuthEncrypt.hs, raaz/Raaz/V1/Digest.hs, raaz/bin/Command/Info.hs
Add strings for more meta information.
=> Info strings

core/Raaz/Core.hs, core/Raaz/Core/KeyExchange.hs, core/Raaz/Core/Memory.hs, core/Raaz/Core/Types/Pointer.hs, core/Raaz/KeyExchange/X25519/Internal.hs, indef/buffer/Buffer.hs, raaz.cabal, raaz/Raaz/Random.hs
some simple refactoring of code
=> some simple code refactoring
