raaz-core/Raaz/Core/Gymnastics.hs
raaz-core/Raaz/Core/Parse/Applicative.hs
raaz-core/Raaz/Core/Write.hs
raaz-core/raaz-core.cabal

Abstracted out the main idea in pointer manipulation that is used by
parsers and writers. The paradigm is general and hence can be used for
many things.

modules for general pointer gymnastics

---

raaz.cabal

The previous version bounds were inaccurate and allowed the cabal
solver to pick configurations which would fail to compile.

Declare more accurate version bounds

---

.gitignore
stack.yaml

Also add ./stack-work to gitignore
I hope PR from master is fine, since this should be a minor change.
Also, I cannot claim to have cross-tested the warnings I got with those one would get on building with `cabal`, since I don't have it.
`stack test` works, but the response has the queer `pending` thing (not sure if it exists with cabal as well):
```
103 examples, 0 failures, 1 pending
```
Update: About moving the build to `stack`, [here's](https://github.com/sakshamsharma/acehack/blob/master/.travis.yml) the `.travis.yml` which I use. Once these steps are done, `stack build` is easily done inside the build container.
Also, there's a need to override some steps in travis' build, otherwise it automatically tries to call `cabal update`, `cabal build` and whatnot. Defeats the purpose, kind …

Add stack.yml file with lts-6.9

---

Raaz/Cipher/AES/Recommendation.hs
Raaz/Core/Memory.hs
Raaz/Core/Types.hs
Raaz/Core/Types/Copying.hs
Raaz/Core/Types/Endian.hs
Raaz/Core/Types/Equality.hs
Raaz/Core/Types/Pointer.hs
Raaz/Core/Util/ByteString.hs
raaz.cabal
spec/Raaz/Cipher/AESSpec.hs
spec/Raaz/Core/EncodeSpec.hs

Using the newtypes Dest and Src we now distinguish the source and destination types in various copy instructions.

add Dest and Src types

---

Raaz/Core/Types/Endian.hs
Raaz/Core/Types/Tuple.hs
cbits/raaz/core/endian.c
spec/Common/Utils.hs
spec/Raaz/Core/Types/WordSpec.hs
spec/Raaz/Hash/Sha1Spec.hs
spec/Raaz/Hash/Sha224Spec.hs
spec/Raaz/Hash/Sha256Spec.hs
spec/Raaz/Hash/Sha384Spec.hs
spec/Raaz/Hash/Sha512Spec.hs

The `EndianStore` class now supports copying between buffers which takes care of endianness. One can use the load and store to define this function however, if used in the context of secure memory, this can lead to secret escaping from the secure memory to the Haskell Heap negating the purpose of secure memory. The copy functions here are implemented either as a memcpy of low level C function. As a result, comparitively lesser secret information escape to the heap.

direct copying between buffers for EndianStore elements.

---

.travis.yml
Raaz/Core/Memory.hs
Raaz/Core/Transfer.hs
Raaz/Core/Types/Tuple.hs
Raaz/Hash/Internal/HMAC.hs
Raaz/Hash/Sha/Util.hs
benchmarks/BlazeVsWrite.hs
raaz.cabal

The `Initialisable` and the `Extractable` class allows memory elements to be initialised by pure values and extract pure values out of memory elements respectively. However pure values are stored in Haskell heap and can get swapped and hence these interfaces are not a good way to initialise or extract sensitive values.
This pull request builds an interface where direct buffer to buffer initialisation/extraction is possible for memory elements. These operations minimise the chances of values escaping into the swap space.

direct initialisation and extraction from memory elements

---

Raaz/Cipher/AES/CBC/Implementation/CPortable.hs
Raaz/Core/Encode/Base16.hs
Raaz/Core/Primitives.hs
Raaz/Core/Random.hs
Raaz/Core/Types/Endian.hs
Raaz/Core/Types/Pointer.hs
Raaz/Hash/Sha224/Implementation/CPortable.hs
Raaz/Hash/Sha384/Implementation/CPortable.hs

this is to fix the irritating warnings due to Applicative and Monoid getting into Prelude.

explicit import of prelude to fix warnings.

---

cbits/raaz/core/endian.c
raaz.cabal

This pull requests makes the following changes
1. All non-windows platforms are assumed to have /dev/urandom
2. Whenever the underlying C compiler is GCC then use `bswap_32` and
`bswap_64` from `byteswap.h` for endian conversion and
adjustments. For all other cases a portable implementation is used.
This pull request is in response to #278.
As a side effect the cabal file has cleaner.

tweaks to the endianness code

---

Raaz/Cipher/AES/CBC/Implementation/CPortable.hs
Raaz/Cipher/AES/Internal.hs
Raaz/Cipher/ChaCha20/Implementation/CPortable.hs
Raaz/Cipher/ChaCha20/Implementation/GCCVector.hs
Raaz/Cipher/ChaCha20/Internal.hs
Raaz/Cipher/Internal.hs
Raaz/Core/Memory.hs
Raaz/Core/Primitives.hs
Raaz/Core/Types/Pointer.hs
Raaz/Hash/Internal.hs
Raaz/Hash/Internal/HMAC.hs
Raaz/Hash/Sha/Util.hs
benchmarks/Cipher.hs
cbits/raaz/cipher/chacha20/vector.c

This pull request added support to specify alignment restrictions on buffers used by implementations.
Each implementations now say what kind of alignment is expected out of a buffer unsing the `BufferAlgorithm` class. On the we performed some cleanup.
1. Got rid of the symmetric class
2. Now has a generic funtion to lift buffer allocations inside memory threads.

interface to capture alignment restrictions of an implementation

---

Raaz/Cipher/AES/CBC/Implementation/CPortable.hs
Raaz/Cipher/AES/Internal.hs
Raaz/Cipher/ChaCha20/Implementation/CPortable.hs
Raaz/Cipher/ChaCha20/Implementation/Vector128.hs
Raaz/Cipher/ChaCha20/Implementation/Vector256.hs
Raaz/Cipher/ChaCha20/Internal.hs
Raaz/Cipher/Internal.hs
Raaz/Core/Encode/Internal.hs
Raaz/Core/Memory.hs
Raaz/Core/MonoidalAction.hs
Raaz/Core/Parse/Applicative.hs
Raaz/Core/Primitives.hs
Raaz/Core/Random.hs
Raaz/Core/Transfer.hs
Raaz/Core/Types/Endian.hs
Raaz/Core/Types/Pointer.hs
Raaz/Core/Types/Tuple.hs
Raaz/Hash/Internal.hs
Raaz/Hash/Internal/HMAC.hs
Raaz/Hash/Sha/Util.hs
Raaz/Hash/Sha1/Implementation/CPortable.hs
Raaz/Hash/Sha224/Implementation/CPortable.hs
Raaz/Hash/Sha256/Implementation/CPortable.hs
Raaz/Hash/Sha384/Implementation/CPortable.hs
Raaz/Hash/Sha512/Implementation/CPortable.hs
spec/Common/Imports.hs
spec/Common/Utils.hs

When peeking/pokeing/loading and storing from pointers, alignment makes or breaks performance.
This series of commits simplify the alignment handling code of raaz. It also adds a separate type
called `Alignment` which _is not_ a length unit but takes care  of alignment.

Pay attention to alignments

---

Raaz/Cipher/ChaCha20/Implementation/CPortable.hs
Raaz/Cipher/ChaCha20/Implementation/Vector256.hs
Raaz/Cipher/ChaCha20/Recommendation.hs
Raaz/Core/Memory.hs
Raaz/Core/Util/ByteString.hs
Raaz/Hash/Internal.hs
Raaz/Hash/Internal/HMAC.hs
Raaz/Random.hs
Raaz/Random/ChaCha20PRG.hs
Reviewing.md

The liftAllocator function is generalised. There is more to explore here. This generalisation should work with the RT monad as well which we have not done.

Release 0.1.0

---

CHANGELOG.md
Raaz/Cipher/AES/Internal.hs
Raaz/Core/Memory.hs
Raaz/Hash/Internal/HMAC.hs
Raaz/Random.hs

Random generation now restricted to certain storable types only. This restricted interface is more honest as
PRGs can essentially only generate random bytes and storables are just glorified sequence of bytes.
Reworked  `RT mem` to behave more like `MT mem`, including a more generic `onSubMemory` etc.

Improving the interface to PRG

---

CHANGELOG.md
Raaz/Cipher/ChaCha20/Recommendation.hs
Raaz/Random.hs
Raaz/Random/ChaCha20PRG.hs
spec/prgquality.sh

Each sampling new updates the key/iv pair so that disclosure of the current state will not compromise
previously generated state. This fixes #314

Hardening of the prg to take care of backward security

---

CHANGELOG.md
entropy/arc4random/Raaz/Entropy.hs
raaz.cabal

- Should use arc4random_buf instead of arc4random

openbsd: entropy use the correct arc4random variant

---

CHANGELOG.md
mans/Makefile
mans/raaz.1.md

The manpage is written in markdown and can be converted to a Unix `groff man` page using `pandoc`.
There is a `Makefile` in the same directory which can be used build the manpage. This should fix #305 at least for time being.

A basic man page for the raaz command

---

appveyor.yml

Appveyor builds to use ghc and cabal directly. This is to support backpack.

appveyor get cabal and ghc directly.

---

appveyor.yml

This pull request tries to enable 32-bit ghc and tools on appveyor. It works towards #360.

appveyor: enable 32-bit and 64-bit builds.

---

benchmarks/Main.hs
benchmarks/internal/Benchmark/CSPRG.hs
implementation/ChaCha20/CHandWritten.hs
implementation/ChaCha20/CPortable.hs
indef/ChaCha20/Implementation.hsig
indef/ChaCha20/PRG.hs
raaz.cabal
tests/entropyquality.sh
tests/prgquality.sh

Verse now exports a variant of chacha20 key stream generator that works with
host endian words. This is meant to be used as a csprg. We incorporate this
into raaz.

chacha specialised for csprg

---

appveyor.yml

this creates an alias to the `cwd` on the drive letter `X:` and makes everything relative to that. This means you gain `length(cwd)-2` of "free" space towards `MAX_PATH`..
Should make the error a bit rarer.

Make MAX_PATH errors more rare on AppVeyor

---

indef/Implementation.hsig
indef/Utils.hs
indef/chacha20/Implementation.hsig
indef/keyed/hash/Implementation.hsig
indef/keyed/hash/Mac/Implementation.hs
raaz/bin/Command/Info.hs

Now that backpack supports working with `KnownNat` constraints instead of explicit definitions, we do not have to fix the Buffer Alignment  through out.

Buffer Alignment definition improved

---

api/aead/Interface.hs
api/random/Interface.hs
api/random/PRGenerator.hs
monocypher/tests/Monocypher/ChaCha20Spec.hs
raaz.cabal
raaz/Raaz/AuthEncrypt.hs
raaz/Raaz/V1/AuthEncrypt.hs

The default lock and lockWith functions now use a randomly generated nouce for each call. This is both simpler (one argument less) and safer (reuse of key nounce prevented) interface.

Better interface for authenticated encryption
